name       : perl-readonly
version    : 2.05
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SA/SANKO/Readonly-2.05.tar.gz : 4b23542491af010d44a5c7c861244738acc74ababae6b8838d354dfb19462b5e
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Readonly - Facility for creating read-only scalars, arrays, hashes
description: |
    This is a facility for creating non-modifiable variables. This is useful for configuration files, headers, etc. It can also be useful as a development and debugging tool for catching updates to variables that should not be changed.
builddeps  :
    - perl-extutils-config
    - perl-extutils-helpers
    - perl-extutils-installpaths
    - perl-module-build-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    $workdir/Build install --destdir=$installdir
check      : |
    $workdir/Build test
